apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stockmanager-v0-0-1
  annotations:
    # use a re-writer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /stockmanagerv0-0-1(/|$)(.*)
        backend:
          serviceName: stockmanagerv0-0-1
          servicePort: 8081
          
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stockmanager-v0-0-2
  annotations:
    # use a re-writer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /stockmanagerv0-0-2(/|$)(.*)
        backend:
          serviceName: stockmanagerv0-0-2
          servicePort: 8081