apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - name: prometheus-server
      protocol: TCP
      port: 9090
    - name: prometheus-pushgateway
      protocol: TCP
      port: 9091
    - name: prometheus-alertmanager
      protocol: TCP
      port: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - name: grafana-server
      protocol: TCP
      port: 3000
